version: '3.8'

services:
  database:
    image: postgres:13
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdatabase
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  
      - "15672:15672" 

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  api:
    build: ./api
    depends_on:
      - database
      - rabbitmq
      - redis
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgres://youruser:yourpassword@database:5432/yourdatabase
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      REDIS_URL: redis://redis:6379

  worker:
    build: ./worker
    depends_on:
      - rabbitmq
      - redis
      - database
    environment:
      DATABASE_URL: postgres://youruser:yourpassword@database:5432/yourdatabase
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      REDIS_URL: redis://redis:6379

volumes:
  db_data:
